#Max number of times you can use /back
#Range: > 0
maxBack = 10
#Max homes
#Range: > 0
maxHomes = 1
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 5
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 5
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 5
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 5
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 5
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 60
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 100
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 100000.0

